// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1p885vyXxkknZJUCrZsk0T7yboQUGt9o',
    appId: '1:414081253209:web:7dc654e98ed952172dd648',
    messagingSenderId: '414081253209',
    projectId: 'petshopsignup',
    authDomain: 'petshopsignup.firebaseapp.com',
    storageBucket: 'petshopsignup.firebasestorage.app',
    measurementId: 'G-DF4R8JTK81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABNTj-cCcRgh3OZTPgrlASajZexZ3I5d4',
    appId: '1:414081253209:android:48a22597509d23d72dd648',
    messagingSenderId: '414081253209',
    projectId: 'petshopsignup',
    storageBucket: 'petshopsignup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0_zl9U6XusAwr54I6g7EKghM_Kl2Lc3E',
    appId: '1:414081253209:ios:d77211dde20d0c142dd648',
    messagingSenderId: '414081253209',
    projectId: 'petshopsignup',
    storageBucket: 'petshopsignup.firebasestorage.app',
    iosBundleId: 'com.example.petShopProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0_zl9U6XusAwr54I6g7EKghM_Kl2Lc3E',
    appId: '1:414081253209:ios:d77211dde20d0c142dd648',
    messagingSenderId: '414081253209',
    projectId: 'petshopsignup',
    storageBucket: 'petshopsignup.firebasestorage.app',
    iosBundleId: 'com.example.petShopProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1p885vyXxkknZJUCrZsk0T7yboQUGt9o',
    appId: '1:414081253209:web:72d4d6e9b7a292b32dd648',
    messagingSenderId: '414081253209',
    projectId: 'petshopsignup',
    authDomain: 'petshopsignup.firebaseapp.com',
    storageBucket: 'petshopsignup.firebasestorage.app',
    measurementId: 'G-FTPYNL17E5',
  );
}
